# Generated by Django 5.2.13 on 2026-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purpose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='balancesnapshot',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='balancesnapshot',
            name='month',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
