# Generated by Django 5.2.13 on 2026-08-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0005_backfill_default_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets_app.household'),
        ),
        migrations.AlterField(
            model_name='category',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='assets_app.household'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='assets_app.household'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('household', 'name')},
        ),
    ]
