# Generated by Django 5.2.13 on 2026-08-20 16:23

import assets_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0006_household_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=assets_app.models.generate_invitation_token, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('owner', '管理者'), ('member', 'メンバー')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=assets_app.models.default_invitation_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='assets_app.household')),
            ],
            options={
                'verbose_name': '招待',
                'verbose_name_plural': '招待',
                'ordering': ['-created_at'],
            },
        ),
    ]
